name: blak smok
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '-g')"
    steps:
    - uses: actions/checkout@v2
    - name: JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'maven'
    - name: patch
      continue-on-error: true
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git submodule update --init --recursive
        ./lazinity patch
    - name: get
      run: tar -czf src.tar.gz Lazinity-* mc-dev
    - uses: actions/upload-artifact@v2
      with:
        name: lazinity-src
        path: src.tar.gz
