name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '-s')"
    steps:
    - uses: actions/checkout@v2
    - name: JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'
    - name: patch
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git submodule update --init --recursive
        ./lazinity patch
    - name: bulid
      run: ./lazinity jar fast ci
    - uses: actions/upload-artifact@v2
      with:
        name: Lazinity-JDK8
        path: lazinity-paperclip.jar
